sudo: false

language: node_js

node_js:
  - node
  - lts/*
  - "9.0"
  - "8.0"
  - "7.0"
  - "6.0"
  - "5.0"
  - "4.0"

stages:
  - lint
  - test

script:
  - npm run test

jobs:
  include:
    - stage: lint
      node_js: node
      script: npm run lint
    - stage: test
      node_js: node
      env: BROWSER=true # Just mark in the Travis UI
      script: npm run browser

after_success:
  - npm run coverage

cache:
  directories:
    - node_modules
