sudo: false

language: node_js

node_js:
  - "4.0"
  - "5.0"
  - "6.0"
  - "7.0"
  - "8.0"
  - "9.0"
  - lts/*

script:
  - npm run lint
  - npm run test

after_success:
  - npm run coverage

cache:
  directories:
    - node_modules
